version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quiz-network

  nodejs-app:
    build: .
    container_name: quiz-app
    restart: always
    depends_on:
      - postgres
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "3000:3000"
    networks:
      - quiz-network

volumes:
  postgres_data:
    name: postgresql-data-quiz

networks:
  quiz-network:
    driver: bridge
