name: Deploy to EC2

on:
  push:
    branches: [main] # or your default branch name

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
  EC2_HOST: ${{ secrets.EC2_HOST }} # Your EC2 instance public IP or domain
  EC2_USERNAME: ${{ secrets.EC2_USERNAME }} # Usually 'ec2-user' for Amazon Linux
  SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }} # Your EC2 instance SSH private key

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest

      - name: Deploy to EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ env.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          # SSH into EC2 and deploy
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ${{ env.EC2_USERNAME }}@${{ env.EC2_HOST }} '

            # Create a shared network if it doesn't exist
            docker network inspect my-network >/dev/null 2>&1 || docker network create my-network

            # Pull the latest image
            docker pull ${{ env.DOCKER_IMAGE }}:latest
            
            # Stop and remove existing containers
            docker stop quiz-app || true
            docker rm quiz-app || true

            docker stop postgresql || true
            docker rm postgresql || true

            # Start PostgreSQL container on the shared network
            docker run -d \
              --name postgresql \
              --network my-network \
              -e POSTGRES_USER=postgres \
              -e POSTGRES_PASSWORD=post123 \
              -e POSTGRES_DB=postgres \
              -p 5432:5432 \
              postgres:alpine

            # Start the app container on the same network
            docker run -d \
              --name quiz-app \
              --network my-network \
              -p 3000:3000 \
              --env-file /home/ec2-user/.env \
              --restart unless-stopped \
              ${{ env.DOCKER_IMAGE }}:latest

            # Verify containers are running
            docker ps
          '
